# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore


class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(685, 595)
		self.webbrowser = QtWebEngineWidgets.QWebEngineView(Form)
		self.webbrowser.setGeometry(QtCore.QRect(10, 10, 681, 581))
		self.webbrowser.setProperty("url", QtCore.QUrl("https://www.hao123.com/"))
		self.webbrowser.setObjectName("webbrowser")

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Form"))


from PyQt5 import QtWebEngineWidgets
